<?php /** @var \Tuum\View\Renderer $this */ ?>

<?php $this->markSectionNoRender('breadcrumb'); ?>

<?php $this->startSection(); ?>

<div class="jumbotron" style="margin-top:20px;">
    <h1>Tuum framework</h1>
    <p>Tuum is yet-another PHP framework for building a web site.</p>
    <p><a href="https://github.com/TuumPHP/" target="_blank">source code≫</a></p>
</div>

<?php $this->endSectionAs('jumbotron'); ?>

<div class="col-md-4">
    <h3><a href="docs/index" >Documents</a></h3>
    <p>Documents on how to install and use the Tuum framework, as well as the background of the design.</p>
    <ul>
        <li><a href="docs/index" >Document Top</a></li>
        <li><a href="#" >Quick Start</a></li>
        <li><a href="#" >Technical Design</a></li>
    </ul>
</div>

<div class="col-md-4">
    <h3><a href="closure/view">Closure Sample</a></h3>
    <p>Samples of pages generated by closures, returning view, text, and array data (json).</p>
</div>

<div class="col-md-4">
    <h3><a href="sample/?name=Tuum+framework" >Controller Sample</a></h3>
    <p>This samples use SampleController class to render various pages.</p>
</div>

<div class="col-md-4">
    <h3><a href="demoTasks" >Demo Task Application</a></h3>
    <p>a demo task application defined as another stack. </p>
</div>


